### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by mvanveen** [mkovacs/nav#1]
attempting to go to ~/test on my os x machine

```
λ. nav
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x13dbc0, 0xc82000a090)
    /usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
main.(*component).commonPrefix(0xc82014e070, 0x0, 0x0, 0x0)
    /Users/mvanveen/tmpgo/src/github.com/mkovacs/nav/main.go:130 +0x33a
main.(*state).input(0xc820035f18, 0x3)
    /Users/mvanveen/tmpgo/src/github.com/mkovacs/nav/main.go:243 +0x1bd
main.main()
    /Users/mvanveen/tmpgo/src/github.com/mkovacs/nav/main.go:28 +0x14e
λ. pwd
```

**Comment by mvanveen** [comment]
does not change directories before panic
